name = "Distribute"
author = "harurusanae"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "624cf864aaef17fc91100084cd7f4d5ac66f5eeebf2e32b345ffd96d0588a687"

[versions]
forge = "43.4.12"
minecraft = "1.19.2"
